import { VidaCobertura, RCOCobertura } from './types';

export const BRAZILIAN_STATES = [
  { value: 'AC', label: 'Acre' },
  { value: 'AL', label: 'Alagoas' },
  { value: 'AP', label: 'Amapá' },
  { value: 'AM', label: 'Amazonas' },
  { value: 'BA', label: 'Bahia' },
  { value: 'CE', label: 'Ceará' },
  { value: 'DF', label: 'Distrito Federal' },
  { value: 'ES', label: 'Espírito Santo' },
  { value: 'GO', label: 'Goiás' },
  { value: 'MA', label: 'Maranhão' },
  { value: 'MT', label: 'Mato Grosso' },
  { value: 'MS', label: 'Mato Grosso do Sul' },
  { value: 'MG', label: 'Minas Gerais' },
  { value: 'PA', label: 'Pará' },
  { value: 'PB', label: 'Paraíba' },
  { value: 'PR', label: 'Paraná' },
  { value: 'PE', label: 'Pernambuco' },
  { value: 'PI', label: 'Piauí' },
  { value: 'RJ', label: 'Rio de Janeiro' },
  { value: 'RN', label: 'Rio Grande do Norte' },
  { value: 'RS', label: 'Rio Grande do Sul' },
  { value: 'RO', label: 'Rondônia' },
  { value: 'RR', label: 'Roraima' },
  { value: 'SC', label: 'Santa Catarina' },
  { value: 'SP', label: 'São Paulo' },
  { value: 'SE', label: 'Sergipe' },
  { value: 'TO', label: 'Tocantins' },
];

export const TIPO_VINCULO_OPTIONS = [
  { value: 'segurado', label: 'Segurado' },
  { value: 'terceiro', label: 'Terceiro' },
  { value: 'corretor', label: 'Corretor' },
  { value: 'advogado', label: 'Advogado' },
  { value: 'procurador', label: 'Procurador' },
  { value: 'conjugue', label: 'Conjugue' },
  { value: 'filho', label: 'Filho(a)' },
  { value: 'preposto', label: 'Preposto' },
  { value: 'familiar', label: 'Familiar' },
];

export const VIDA_COBERTURA_OPTIONS: { value: VidaCobertura; label: string }[] = [
  { value: 'cancer_infantil', label: 'Sinistro diagnóstico de câncer infantil' },
  { value: 'dit_acidente_titular', label: 'Sinistro diárias por incapacidade temporária – DIT - Acidente do segurado principal - Titular' },
  { value: 'dit_doenca_titular', label: 'Sinistro diárias por incapacidade temporária (DIT) - Doença do titular (Segurado principal)' },
  { value: 'dmho', label: 'Sinistro DMHO – Despesas médicas, hospitalares e odontológicas' },
  { value: 'doencas_graves_titular', label: 'Sinistro doenças graves - Titular - Segurado principal' },
  { value: 'invalidez_funcional_doenca_titular', label: 'Sinistro invalidez funcional permanente por doença do titular - Segurado principal.' },
  { value: 'invalidez_permanente_acidente_titular', label: 'Sinistro - Invalidez permanente total e/ou parcial por acidente do titular - Segurado principal' },
  { value: 'morte_acidental_conjuge', label: 'Sinistro morte acidental de cônjuge' },
  { value: 'morte_acidental_filhos', label: 'Sinistro – Morte Acidental de Filhos(as)' },
  { value: 'morte_acidental_titular', label: 'Sinistro - Morte acidental - Titular - Segurado principal' },
  { value: 'morte_natural_conjuge', label: 'Sinistro morte natural – Cônjuge' },
  { value: 'morte_natural_filhos', label: 'Sinistro morte natural – Filhos' },
  { value: 'morte_natural_titular', label: 'Sinistro morte natural - Titular - Segurado principal' },
  { value: 'reembolso_funeral', label: 'Sinistro - Reembolso funeral - Individual, familiar e estendida' },
];

export const RCO_COBERTURA_OPTIONS: { value: RCOCobertura; label: string }[] = [
  { value: 'danos_materiais', label: 'Danos Materiais' },
  { value: 'danos_corporais', label: 'Danos Corporais' },
  { value: 'danos_morais', label: 'Danos Morais' },
  { value: 'despesas', label: 'Despesas' },
];

export const DOCUMENT_TYPES: Record<VidaCobertura | RCOCobertura, string[]> = {
  cancer_infantil: [
    'Cópia do RG ou documento de identificação do segurado',
    'Cópia do CPF do segurado',
    'Cópia do comprovante de residência',
    'Cópia do RG/RNE e CPF do(a) mãe/pai ou responsável legal',
    'Comprovante de residência do(a) mãe/pai ou responsável legal',
    'Comunicado de sinistro com informações médicas',
    'Laudo de diagnóstico da doença elaborado por médico habilitado em oncologia',
    'Laudo de exames citológicos e histológicos conclusivo',
    'Formulário de autorização para crédito da indenização em conta corrente',
    'Comprovante das despesas efetuadas com o tratamento coberto para os menores de 14 anos',
  ],
  dit_acidente_titular: [
    'Aviso de Sinistro preenchido pelo reclamante',
    'Cópia autenticada do Boletim de Ocorrência',
    'Cópia simples do Comunicado de Acidente de Trabalho (C.A.T.), se for o caso',
    'Cópia simples da Carteira Nacional de Habilitação (CNH) do segurado',
    'Cópia simples do prontuário ou ficha médica hospitalar',
    'Cópia simples do RG, CPF e comprovante de residência',
    'Cópia simples dos resultados de exames realizados',
    'Prontuário médico hospitalar completo (em caso de cirurgia)',
    'Formulário de Autorização para Crédito em conta corrente',
    'Formulário do registro de informações cadastrais – Pessoa Física',
  ],
  dit_doenca_titular: [
    'Aviso de Sinistro preenchido pelo reclamante e médico',
    'Cópia simples do RG, CPF e Comprovante de residência',
    'Cópia simples dos resultados de exames realizados',
    'Prontuário médico hospitalar completo (em caso de cirurgia)',
    'Formulário de Autorização para Crédito em conta corrente',
    'Formulário do registro de informações cadastrais - pessoa física',
  ],
  dmho: [
    'Formulário de Aviso de Sinistro',
    'Cópias autenticadas do RG, CPF e comprovante de residência do segurado',
    'Comprovantes originais de todas as despesas médicas, hospitalares e odontológicas',
    'Resultados de todos os exames realizados',
    'Cópia autenticada da CAT, quando aplicável',
    'Cópia autenticada do Boletim de Ocorrência Policial, quando aplicável',
    'Cópia autenticada da CNH do segurado, quando aplicável',
  ],
  doencas_graves_titular: [
    'Aviso de Sinistro preenchido',
    'Cópias simples dos exames e laudos realizados',
    'Cópia simples do RG, CPF e comprovante de residência',
    'Formulário de Autorização para Crédito em Conta Corrente',
    'Formulário de Registro de Informações Cadastrais – Pessoa Física',
  ],
  invalidez_funcional_doenca_titular: [
    'Aviso de Sinistro preenchido',
    'Cópia simples do RG, CPF e comprovante de residência',
    'Cópia simples dos exames e laudos realizados',
    'Formulário de Autorização para Crédito em Conta',
    'Formulário de Registro de Informações Cadastrais – Pessoa Física',
  ],
  invalidez_permanente_acidente_titular: [
    'Aviso de Sinistro preenchido',
    'Cópia simples do primeiro atendimento hospitalar',
    'Cópias simples dos exames e laudos realizados',
    'Cópia autenticada do laudo de corpo de delito',
    'Cópia simples do RG, CPF e comprovante de residência',
    'Cópia simples da CNH do segurado',
    'Cópia autenticada do boletim de ocorrência',
    'Cópia simples da Comunicação de Acidente de Trabalho',
    'Formulário de autorização para crédito em conta corrente',
    'Formulário do registro de informações cadastrais – pessoa física',
  ],
  morte_acidental_conjuge: [
    'Aviso de sinistro preenchido',
    'Cópia autenticada da certidão de óbito',
    'Cópia simples do RG, CPF e comprovante de residência',
    'Cópia autenticada da certidão de casamento atualizada',
    'Cópia autenticada do boletim de ocorrência',
    'Cópia simples da comunicação de acidente de trabalho (CAT)',
    'Cópia simples do laudo de necrópsia',
    'Cópia simples dos resultados dos exames complementares',
    'Cópia simples da CNH do(a) sinistrado(a)',
    'Cópia simples do prontuário ou ficha médica hospitalar',
  ],
  morte_acidental_filhos: [
    'Aviso de Sinistro preenchido',
    'Cópia autenticada da Certidão de Óbito',
    'Cópia simples da Certidão de Nascimento',
    'Cópia simples do RG e CPF',
    'Cópia autenticada do Boletim de Ocorrência',
    'Cópia simples do Laudo de Necrópsia',
    'Cópia simples dos resultados de exames complementares',
    'Cópia simples da CNH do(a) sinistrado(a)',
    'Cópia simples do prontuário ou ficha médica hospitalar',
  ],
  morte_acidental_titular: [
    'Aviso de Sinistro preenchido',
    'Cópia autenticada da Certidão de Óbito',
    'Cópia simples do RG, CPF e Comprovante de residência',
    'Cópia autenticada do Boletim de Ocorrência',
    'Cópia simples da Comunicação de Acidente de Trabalho (CAT)',
    'Cópia simples do Laudo de Necrópsia',
    'Cópia simples dos resultados dos exames complementares',
    'Cópia simples da CNH do segurado',
    'Cópia simples do prontuário ou ficha médica hospitalar',
  ],
  morte_natural_conjuge: [
    'Aviso de Sinistro preenchido',
    'Cópia autenticada da Certidão de Óbito',
    'Cópia simples do RG, CPF e comprovante de residência',
    'Cópia autenticada da Certidão de Casamento atualizada',
  ],
  morte_natural_filhos: [
    'Aviso de Sinistro preenchido',
    'Cópia autenticada da Certidão de Óbito',
    'Cópia autenticada da Certidão de Nascimento',
    'Cópia simples do RG e CPF',
  ],
  morte_natural_titular: [
    'Aviso de Sinistro preenchido',
    'Cópia autenticada da Certidão de Óbito',
    'Cópia simples do RG, CPF e Comprovante de residência',
  ],
  reembolso_funeral: [
    'Cópia autenticada da certidão de óbito',
    'Cópia simples do RG, CPF e Comprovante de residência',
    'Cópia simples do RG, CPF e comprovante de residência do Responsável',
    'Nota Fiscal Eletrônica com a discriminação dos serviços prestados',
    'Dados Bancários de quem pagou ou custeou o funeral',
  ],
  danos_materiais: [
    'Aviso de sinistro segurado',
    'Aviso do terceiro (com os dados da oficina)',
    'CNH E CRLV do segurado',
    'CNH E CRLV do terceiro',
    'Boletim de ocorrência',
    'Fotos dos danos do veículo terceiro',
    'Fotos do veículo segurado após o acidente',
    'Vídeo do momento do acidente',
  ],
  danos_corporais: [
    'Aviso de sinistro segurado',
    'Aviso do terceiro (se houve a reclamação)',
    'Contato das vítimas',
    'Documento pessoal das vítimas',
    'CNH E CRLV do segurado',
    'Boletim de ocorrência',
    'Documentos médicos',
    'Vídeo do momento do acidente',
  ],
  danos_morais: [
    'Aviso de sinistro segurado',
    'Aviso do terceiro',
    'CNH E CRLV do segurado',
    'Boletim de ocorrência',
    'Documentação relacionada ao dano moral',
  ],
  despesas: [
    'Aviso de sinistro segurado',
    'Comprovantes de despesas',
    'CNH E CRLV do segurado',
    'Boletim de ocorrência',
  ],
};
